---
    postgresqlconf:
        max_connections: 99
        superuser_reserved_connections: 3
        shared_buffers: 12800MB
        huge_pages: try
        max_prepared_transactions: 0
        work_mem: 4MB
        maintenance_work_mem: 64MB
        replacement_sort_tuples: 150000
        max_stack_depth: 2MB
        vacuum_cost_delay: 0
        vacuum_cost_page_hit: 1
        vacuum_cost_page_miss: 10
        vacuum_cost_page_dirty: 20
        vacuum_cost_limit: 200
        bgwriter_delay: 200ms
        bgwriter_lru_maxpages: 100
        bgwriter_lru_multiplier: 2.0
        wal_level: minimal
        synchronous_commit: on
        wal_sync_method: fsync
        wal_log_hints: off
        wal_compression: off
        wal_writer_delay: 200ms
        wal_writer_flush_after: 1MB
        commit_delay: 0
        commit_siblings: 5
        checkpoint_timeout: 1d
        max_wal_size: 10GB
        min_wal_size: 890mb
        checkpoint_completion_target: 0.9
        checkpoint_flush_after: 256kB
        checkpoint_warning: 30s
        archive_mode: off
        archive_command: 'bob'
        archive_timeout: 0
        enable_bitmapscan: on
        enable_hashagg: on
        enable_hashjoin: on
        enable_indexscan: on
        enable_indexonlyscan: on
        enable_material: on
        enable_mergejoin: on
        enable_nestloop: on
        enable_seqscan: on
        enable_sort: on
        enable_tidscan: on
        log_destination: stderr
        logging_collector: off
        client_min_messages: notice
        log_min_messages: warning
        log_min_error_statement: error
        log_min_duration_statement: -1
        debug_print_parse: off
        debug_print_rewritten: off
        debug_print_plan: off
        debug_pretty_print: on
        log_checkpoints: off
        log_connections: off
        log_disconnections: off
        log_duration: off
        log_error_verbosity: default
        log_hostname: off
        log_line_prefix: "'%m [%p] '"
        log_lock_waits: off
        log_statement: none
        log_temp_files: -1
        track_activities: on
        track_counts: on
        track_io_timing: off
        track_functions: none
        track_activity_query_size: 1024
        log_parser_stats: off
        log_planner_stats: off
        log_executor_stats: off
        log_statement_stats: off
        autovacuum: on
        log_autovacuum_min_duration: -1
        autovacuum_max_workers: 3
        autovacuum_naptime: 1min
        autovacuum_vacuum_threshold: 50
        autovacuum_analyze_threshold: 50
        autovacuum_vacuum_scale_factor: 0.2
        autovacuum_analyze_scale_factor: 0.1
        autovacuum_freeze_max_age: 200000000
        autovacuum_multixact_freeze_max_age: 400000000
        autovacuum_vacuum_cost_delay: 20ms
        autovacuum_vacuum_cost_limit: -1
