---
    X:
        noclassgc: false
    XX:
        AggressiveHeap: false
        DisableExplicitGC: false
        InitialHeapSize_Percent: 0
        MaxGCPauseMillis: 0
        MaxHeapSize_Percent: 100
        MaxHeapFreeRatio: 0
        MaxMetaspaceSize: 0
        MaxNewSize_Percent: 50
        MaxTenuringThreshold: 0
        MinHeapFreeRatio: 0
        NewRatio: 0
        NewSize_Percent: 50
        ParallelGCThreads: 0
        ParallelRefProcEnabled: false
